Update base for Update on "[WIP] faketensor cpp: add tests"
add, mm, split, cat, shape env, symints, context manager, make_fx

tests that fail: 
1. symint split

```bash
Traceback (most recent call last):
  File "/home/liangel/local/pytorch/test/test_faketensor_cpp.py", line 228, in test_symbolic_shapes_split
    parts = torch.split(x, 2, dim=0)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangel/local/pytorch/torch/functional.py", line 173, in split
    return tensor.split(split_size_or_sections, dim)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liangel/local/pytorch/torch/_tensor.py", line 1065, in split
    return torch._VF.split(self, split_size, dim)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 0 INTERNAL ASSERT FAILED at "/home/liangel/local/pytorch/torch/csrc/utils/python_arg_parser.cpp":648, please report a bug to PyTorch. dispatch_on_subclass called with NO overloaded args that actually triggered dispatch, perhaps there is a divergence in how you detect torch function/dispatch and how overloaded args is computed?  overloaded_args = [0x7eff2d0738e0], is_mode_active = 0
```

this test fails because split is a CompositeExplicitAutograd op with no Meta kernel --> needs decomp table

2. make_fx integration needs more work, need to integrate with proxy_tensor




[ghstack-poisoned]