[BE][EZ] Avoid redundant vector copies
I.e. instead of
```
std::vector<int> foo;
foo = fn();
return foo;
```
just
```
return fn);
```

And create vector object only when it's going ot be used

And workaround gcc-13.3 false-positvie free-nonheap-object error, i.e.
```
In file included from /usr/include/x86_64-linux-gnu/c++/13/bits/c++allocator.h:33,
                 from /usr/include/c++/13/bits/allocator.h:46,
                 from /usr/include/c++/13/string:43,
                 from /usr/include/c++/13/bits/locale_classes.h:40,
                 from /usr/include/c++/13/bits/ios_base.h:41,
                 from /usr/include/c++/13/streambuf:43,
                 from /usr/include/c++/13/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/13/iterator:66,
                 from /var/lib/jenkins/workspace/c10/util/irange.h:9,
                 from /var/lib/jenkins/workspace/torch/csrc/jit/passes/onnx/constant_map.cpp:1:
In member function 'void std::__new_allocator<_Tp>::deallocate(_Tp*, size_type) [with _Tp = c10::ShapeSymbol]',
    inlined from 'constexpr void std::allocator< <template-parameter-1-1> >::deallocate(_Tp*, std::size_t) [with _Tp = c10::ShapeSymbol]' at /usr/include/c++/13/bits/allocator.h:210:35,
    inlined from 'static constexpr void std::allocator_traits<std::allocator<_CharT> >::deallocate(allocator_type&, pointer, size_type) [with _Tp = c10::ShapeSymbol]' at /usr/include/c++/13/bits/alloc_traits.h:517:23,
    inlined from 'constexpr void std::_Vector_base<_Tp, _Alloc>::_M_deallocate(pointer, std::size_t) [with _Tp = c10::ShapeSymbol; _Alloc = std::allocator<c10::ShapeSymbol>]' at /usr/include/c++/13/bits/stl_vector.h:390:19,
    inlined from 'constexpr std::_Vector_base<_Tp, _Alloc>::~_Vector_base() [with _Tp = c10::ShapeSymbol; _Alloc = std::allocator<c10::ShapeSymbol>]' at /usr/include/c++/13/bits/stl_vector.h:369:15,
    inlined from 'constexpr std::vector<_Tp, _Alloc>::~vector() [with _Tp = c10::ShapeSymbol; _Alloc = std::allocator<c10::ShapeSymbol>]' at /usr/include/c++/13/bits/stl_vector.h:738:7,
    inlined from 'constexpr void std::_Optional_payload_base<_Tp>::_M_destroy() [with _Tp = std::vector<c10::ShapeSymbol>]' at /usr/include/c++/13/optional:287:35,
    inlined from 'constexpr void std::_Optional_payload_base<_Tp>::_M_reset() [with _Tp = std::vector<c10::ShapeSymbol>]' at /usr/include/c++/13/optional:318:14,
    inlined from 'constexpr std::_Optional_payload<_Tp, false, _Copy, _Move>::~_Optional_payload() [with _Tp = std::vector<c10::ShapeSymbol>; bool _Copy = false; bool _Move = false]' at /usr/include/c++/13/optional:441:65,
    inlined from 'constexpr std::_Optional_base<std::vector<c10::ShapeSymbol>, false, false>::~_Optional_base()' at /usr/include/c++/13/optional:512:12,
    inlined from 'constexpr std::optional<std::vector<c10::ShapeSymbol> >::~optional()' at /usr/include/c++/13/optional:707:11,
    inlined from 'static std::optional<std::vector<long int> > torch::jit::ConstantValueMap::GetShapeInto1DInt64VectorWithOneUnknown(const std::string&)' at /var/lib/jenkins/workspace/torch/csrc/jit/passes/onnx/constant_map.cpp:143:5:
/usr/include/c++/13/bits/new_allocator.h:172:33: error: 'void operator delete(void*, std::size_t)' called on pointer '<unknown>' with nonzero offset [8, 9223372036854775800] [-Werror=free-nonheap-object]
  172 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                 ^
In member function '_Tp* std::__new_allocator<_Tp>::allocate(size_type, const void*) [with _Tp = c10::ShapeSymbol]',
    inlined from 'constexpr _Tp* std::allocator< <template-parameter-1-1> >::allocate(std::size_t) [with _Tp = c10::ShapeSymbol]' at /usr/include/c++/13/bits/allocator.h:198:40,
    inlined from 'static constexpr _Tp* std::allocator_traits<std::allocator<_CharT> >::allocate(allocator_type&, size_type) [with _Tp = c10::ShapeSymbol]' at /usr/include/c++/13/bits/alloc_traits.h:482:28,
    inlined from 'constexpr std::_Vector_base<_Tp, _Alloc>::pointer std::_Vector_base<_Tp, _Alloc>::_M_allocate(std::size_t) [with _Tp = c10::ShapeSymbol; _Alloc = std::allocator<c10::ShapeSymbol>]' at /usr/include/c++/13/bits/stl_vector.h:381:33,
    inlined from 'constexpr void std::_Vector_base<_Tp, _Alloc>::_M_create_storage(std::size_t) [with _Tp = c10::ShapeSymbol; _Alloc = std::allocator<c10::ShapeSymbol>]' at /usr/include/c++/13/bits/stl_vector.h:398:44,
    inlined from 'constexpr std::_Vector_base<_Tp, _Alloc>::_Vector_base(std::size_t, const allocator_type&) [with _Tp = c10::ShapeSymbol; _Alloc = std::allocator<c10::ShapeSymbol>]' at /usr/include/c++/13/bits/stl_vector.h:335:26,
    inlined from 'constexpr std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = c10::ShapeSymbol; _Alloc = std::allocator<c10::ShapeSymbol>]' at /usr/include/c++/13/bits/stl_vector.h:603:61,
    inlined from 'constexpr void std::_Construct(_Tp*, _Args&& ...) [with _Tp = vector<c10::ShapeSymbol>; _Args = {const vector<c10::ShapeSymbol, allocator<c10::ShapeSymbol> >&}]' at /usr/include/c++/13/bits/stl_construct.h:119:7,
    inlined from 'constexpr void std::_Optional_payload_base<_Tp>::_M_construct(_Args&& ...) [with _Args = {const std::vector<c10::ShapeSymbol, std::allocator<c10::ShapeSymbol> >&}; _Tp = std::vector<c10::ShapeSymbol>]' at /usr/include/c++/13/optional:278:19,
    inlined from 'constexpr std::_Optional_payload_base<_Tp>::_Optional_payload_base(bool, const std::_Optional_payload_base<_Tp>&) [with _Tp = std::vector<c10::ShapeSymbol>]' at /usr/include/c++/13/optional:145:22,
    inlined from 'constexpr std::_Optional_payload<std::vector<c10::ShapeSymbol>, true, false, false>::_Optional_payload(bool, const std::_Optional_payload_base<std::vector<c10::ShapeSymbol> >&) [inherited from std::_Optional_payload_base<std::vector<c10::ShapeSymbol> >]' at /usr/include/c++/13/optional:399:42,
    inlined from 'constexpr std::_Optional_payload<std::vector<c10::ShapeSymbol>, false, false, false>::_Optional_payload(bool, const std::_Optional_payload_base<std::vector<c10::ShapeSymbol> >&) [inherited from std::_Optional_payload_base<std::vector<c10::ShapeSymbol> >]' at /usr/include/c++/13/optional:433:57,
    inlined from 'constexpr std::_Optional_base<_Tp, <anonymous>, <anonymous> >::_Optional_base(const std::_Optional_base<_Tp, <anonymous>, <anonymous> >&) [with _Tp = std::vector<c10::ShapeSymbol>; bool <anonymous> = false; bool <anonymous> = false]' at /usr/include/c++/13/optional:540:9,
    inlined from 'constexpr std::optional<std::vector<c10::ShapeSymbol> >::optional(const std::optional<std::vector<c10::ShapeSymbol> >&)' at /usr/include/c++/13/optional:707:11,
    inlined from 'std::optional<std::vector<c10::ShapeSymbol> > c10::SymbolicShape::sizes() const' at /var/lib/jenkins/workspace/aten/src/ATen/core/jit_type.h:436:12,
    inlined from 'static std::optional<std::vector<long int> > torch::jit::ConstantValueMap::GetShapeInto1DInt64VectorWithOneUnknown(const std::string&)' at /var/lib/jenkins/workspace/torch/csrc/jit/passes/onnx/constant_map.cpp:128:48:
```

ghstack-source-id: 43082a43e93b25f0e3f1350131f89dc76b6ddb35
Pull-Request: https://github.com/pytorch/pytorch/pull/178389